# Generated by Django 5.0.6 on 2024-07-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('text', models.TextField(max_length=150, verbose_name='本文')),
                ('image', models.ImageField(upload_to='media/images', verbose_name='画像')),
                ('good', models.IntegerField(blank=True, default=0, null=True, verbose_name='いいね')),
                ('read', models.IntegerField(blank=True, default=0, null=True, verbose_name='閲覧数')),
                ('usertext', models.CharField(blank=True, default='a', max_length=50, null=True, verbose_name='紐付け')),
            ],
        ),
    ]
