# Generated by Django 5.0.6 on 2024-07-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='duedate',
            field=models.DateTimeField(null=True, verbose_name='期限'),
        ),
        migrations.AddField(
            model_name='post',
            name='priority',
            field=models.CharField(choices=[('high', 'primary'), ('normal', 'info'), ('low', 'success')], max_length=50, null=True, verbose_name='優先度'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='media/images', verbose_name='画像'),
        ),
    ]
