# Generated by Django 5.0.6 on 2024-07-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_post_duedate_post_priority_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='post',
            name='priority',
            field=models.CharField(choices=[('danger', 'high'), ('info', 'normal'), ('success', 'low')], max_length=50, null=True, verbose_name='優先度'),
        ),
    ]
