# Generated by Django 5.0.6 on 2024-07-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_post_image_alter_post_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='duedate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='期限'),
        ),
    ]
